import { StyleSheet, StatusBar } from "react-native";
export default StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "#1a1a1a",
		alignItems: "center",
		paddingHorizontal: 15,
		paddingTop: StatusBar.currentHeight,
	},
	backButton: {
		flexDirection: "row",
		alignSelf: "flex-start",
		marginTop: 0,
		marginBottom: 10,
		alignItems: "center",
	},
	backButtonText: {
		color: "#00ff00",
		fontSize: 18,
		marginLeft: 5,
	},
	header: {
		fontSize: 32,
		fontWeight: "bold",
		color: "#ffffff",
		marginBottom: 30,
	},
	routineInfo: {
		backgroundColor: "rgba(51, 51, 51, 0.7)",
		borderRadius: 15,
		padding: 20,
		width: "90%",
		marginBottom: 40,
		alignItems: "center",
		borderWidth: 1,
		borderColor: "#00ff00",
	},
	routineName: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#00ff00",
		marginBottom: 10,
		textAlign: "center",
	},
	routineDetails: {
		fontSize: 16,
		color: "#e0e0e0",
		marginBottom: 5,
		textAlign: "center",
	},
	noRoutineText: {
		fontSize: 18,
		color: "#aaaaaa",
		marginBottom: 50,
	},
	timerPlaceholder: {
		backgroundColor: "#00ff00",
		borderRadius: 150,
		width: 250,
		height: 250,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 50,
		elevation: 5,
		shadowColor: "#00ff00",
		shadowOffset: { width: 0, height: 2 },
		shadowOpacity: 0.8,
		shadowRadius: 3,
	},
	timerText: {
		fontSize: 60,
		fontWeight: "bold",
		color: "#1a1a1a",
	},
	currentPhaseText: {
		fontSize: 24,
		fontWeight: "bold",
		color: "#1a1a1a",
		marginTop: 5,
	},
	controls: {
		flexDirection: "row",
		justifyContent: "space-around",
		width: "100%",
	},
	controlButton: {
		backgroundColor: "#333333",
		width: 120,
		height: 120,
		borderRadius: 60,
		justifyContent: "center",
		alignItems: "center",
		borderWidth: 1,
		borderColor: "#ffffff",
	},
	controlButtonText: {
		color: "#ffffff",
		fontSize: 18,
		marginTop: 5,
	},
});
